export interface GeneralModelOption {
  value: string;
  label: string;
  description: string;
  context_window_tokens: number;
  pricing_input_usd_per_million: number;
  pricing_output_usd_per_million: number;
}

export const GENERAL_CHAT_MODELS: GeneralModelOption[] = [
  {
    value: 'openai/gpt-4o-mini',
    label: 'GPT-4o Mini',
    description: 'Лучший бюджетный дефолт для повседневного общения, быстрых ответов и недорогих диалогов.',
    context_window_tokens: 128_000,
    pricing_input_usd_per_million: 0.15,
    pricing_output_usd_per_million: 0.60,
  },
  {
    value: 'google/gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    description: 'Быстрый reasoning-вариант с большим контекстом, когда нужен баланс цены и “умности”.',
    context_window_tokens: 1_048_576,
    pricing_input_usd_per_million: 0.30,
    pricing_output_usd_per_million: 2.50,
  },
  {
    value: 'openrouter/free',
    label: 'OpenRouter Free Router',
    description: 'Автоматический бесплатный роутер OpenRouter: удобный выбор, когда важнее нулевая цена, чем конкретная модель.',
    context_window_tokens: 200_000,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'deepseek/deepseek-v4-flash:free',
    label: 'DeepSeek V4 Flash Free',
    description: 'Бесплатный быстрый вариант с очень большим контекстом для обычных чатов, анализа и длинных обсуждений.',
    context_window_tokens: 1_048_576,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'qwen/qwen3-coder:free',
    label: 'Qwen3 Coder 480B Free',
    description: 'Сильная бесплатная coding-friendly модель для вопросов по коду, архитектуре, отладке и технических диалогов.',
    context_window_tokens: 1_048_576,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'openai/gpt-oss-120b:free',
    label: 'GPT-OSS 120B Free',
    description: 'Большая бесплатная open-weight модель OpenAI для reasoning, текстовых задач и вдумчивых ответов.',
    context_window_tokens: 131_072,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'meta-llama/llama-3.3-70b-instruct:free',
    label: 'Llama 3.3 70B Free',
    description: 'Надёжная бесплатная instruct-модель для повседневного общения, идей, черновиков и объяснений.',
    context_window_tokens: 131_072,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'z-ai/glm-5.1',
    label: 'GLM 5.1 Free',
    description: 'Бесплатный сильный универсальный чат с большим контекстом, reasoning-параметрами и поддержкой инструментов.',
    context_window_tokens: 202_800,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'nvidia/nemotron-3-super-120b-a12b:free',
    label: 'Nemotron 3 Super Free',
    description: 'Бесплатная крупная модель NVIDIA для сложных вопросов, структурированных ответов и длинного контекста.',
    context_window_tokens: 1_000_000,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'openrouter/owl-alpha',
    label: 'Owl Alpha Free',
    description: 'Бесплатная long-context модель OpenRouter для агентных сценариев, структурированных ответов и tool-use задач.',
    context_window_tokens: 1_048_756,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'minimax/minimax-m2.5:free',
    label: 'MiniMax M2.5 Free',
    description: 'Бесплатная быстрая модель для лёгких чатов, коротких ответов, идей и повседневных запросов.',
    context_window_tokens: 204_800,
    pricing_input_usd_per_million: 0,
    pricing_output_usd_per_million: 0,
  },
  {
    value: 'openai/gpt-5.4-mini',
    label: 'GPT-5.4 Mini',
    description: 'Сильный modern-balanced вариант для чатов, где хочется лучшее качество без premium-цены.',
    context_window_tokens: 400_000,
    pricing_input_usd_per_million: 0.75,
    pricing_output_usd_per_million: 4.50,
  },
  {
    value: 'anthropic/claude-haiku-4.5',
    label: 'Claude Haiku 4.5',
    description: 'Очень приятная быстрая модель для живого стиля ответа, summaries и частых коротких запросов.',
    context_window_tokens: 200_000,
    pricing_input_usd_per_million: 1.00,
    pricing_output_usd_per_million: 5.00,
  },
  {
    value: 'google/gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    description: 'Сильный вариант для длинного контекста, сложного reasoning и вдумчивых ответов.',
    context_window_tokens: 1_048_576,
    pricing_input_usd_per_million: 1.25,
    pricing_output_usd_per_million: 10.00,
  },
  {
    value: 'moonshotai/kimi-k2.6',
    label: 'Kimi K2.6',
    description: 'Новая creative-coding модель Moonshot AI для длинного контекста, UI/UX генерации, агентных задач и сложных лендингов с полноценным HTML preview.',
    context_window_tokens: 262_144,
    pricing_input_usd_per_million: 0.75,
    pricing_output_usd_per_million: 3.50,
  },
  {
    value: 'moonshotai/kimi-k2.5',
    label: 'Kimi K2.5',
    description: 'Сильный long-context и orchestration-first вариант для больших аналитических задач, planning-heavy запросов и fullstack-разработки.',
    context_window_tokens: 262_144,
    pricing_input_usd_per_million: 0.3827,
    pricing_output_usd_per_million: 1.72,
  },
  {
    value: 'openai/gpt-4o',
    label: 'GPT-4o',
    description: 'Стабильный premium-класс для качественного мультимодального общения и общего использования.',
    context_window_tokens: 128_000,
    pricing_input_usd_per_million: 2.50,
    pricing_output_usd_per_million: 10.00,
  },
  {
    value: 'openai/gpt-5.4',
    label: 'GPT-5.4',
    description: 'Флагманский general-purpose вариант, когда нужен максимально сильный обычный чат.',
    context_window_tokens: 1_050_000,
    pricing_input_usd_per_million: 2.50,
    pricing_output_usd_per_million: 15.00,
  },
  {
    value: 'anthropic/claude-sonnet-4.6',
    label: 'Claude Sonnet 4.6',
    description: 'Очень сильный quality-first вариант для содержательных ответов, письма и сложных обсуждений.',
    context_window_tokens: 1_000_000,
    pricing_input_usd_per_million: 3.00,
    pricing_output_usd_per_million: 15.00,
  },
];
